# Site Data
title: "The Blacklist"
tagline: " — Crossed off every list. "
name: "DonGato"
author_bio:
  "A digital nomad."
description: "A Digital Garden."
footer_description:
  'The phrase "digital garden" is a metaphor for thinking about writing and creating.'
notes_url: "://don-gato-coded.github.io/"
profile_pic: /assets/img/avatars/gato1.jpeg
favicon: /assets/img/favicon.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://theblacklist.qzz.io" # the base hostname & protocol for your site, e.g. https://example.com
permalink: /posts/:title.html
theme_color: white
encoding: utf-8

# Links and Social Media
repository: https://github.com/brennanbrown/enjoyment-work
github: https://github.com/don-gato-coded
twitter: https://x.com/Miblanco4

# portfolio: https://brennanbrown.ca
email: don-gato-coded@gmail.com

# Build Settings
theme: null
plugins:
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier
  - jekyll-toc

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

JEKYLL_ENV: "production"

collections:
  notes:
    output: true
    permalink: /notes/:title
  journals:
    output: true
    permalink: /journals/:title
  pages:
    output: true
    permalink: /page/:name

disqus:
  shortname: journalbar

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
      category: "Post"
      toc: false
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: post
      content-type: journals
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      content-type: pages

jekyll-archives:
  enabled: []
  layout: default
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no-toc
  list_class: section-nav
  sublist_class: ""
  item_class: entry
  item_prefix: toc-'

facebook: https://www.facebook.com/kellyjamestellez
spotify: https://open.spotify.com/user/blacklist3d
instagram: https://www.instagram.com/elgatokjt/


  